/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTransaccionesRouteImport } from './routes/_authenticated/transacciones'
import { Route as AuthenticatedTercerosRouteImport } from './routes/_authenticated/terceros'
import { Route as AuthenticatedTasaParalelaRouteImport } from './routes/_authenticated/tasa-paralela'
import { Route as AuthenticatedTasaRouteImport } from './routes/_authenticated/tasa'
import { Route as AuthenticatedRegistrarRouteImport } from './routes/_authenticated/registrar'
import { Route as AuthenticatedProveedoresRouteImport } from './routes/_authenticated/proveedores'
import { Route as AuthenticatedPlanCuentasRouteImport } from './routes/_authenticated/plan-cuentas'
import { Route as AuthenticatedPagarCxpRouteImport } from './routes/_authenticated/pagar-cxp'
import { Route as AuthenticatedOffBalanceRouteImport } from './routes/_authenticated/off-balance'
import { Route as AuthenticatedInicioRouteImport } from './routes/_authenticated/inicio'
import { Route as AuthenticatedGypRouteImport } from './routes/_authenticated/gyp'
import { Route as AuthenticatedFcRouteImport } from './routes/_authenticated/fc'
import { Route as AuthenticatedDiferencialCambiarioRouteImport } from './routes/_authenticated/diferencial-cambiario'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCxpRouteImport } from './routes/_authenticated/cxp'
import { Route as AuthenticatedCxcRouteImport } from './routes/_authenticated/cxc'
import { Route as AuthenticatedCuentasBancariasRouteImport } from './routes/_authenticated/cuentas-bancarias'
import { Route as ApiPublicHooksSyncParalelaRouteImport } from './routes/api/public/hooks/sync-paralela'
import { Route as ApiPublicHooksSyncBcvRouteImport } from './routes/api/public/hooks/sync-bcv'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTransaccionesRoute =
  AuthenticatedTransaccionesRouteImport.update({
    id: '/transacciones',
    path: '/transacciones',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTercerosRoute = AuthenticatedTercerosRouteImport.update({
  id: '/terceros',
  path: '/terceros',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTasaParalelaRoute =
  AuthenticatedTasaParalelaRouteImport.update({
    id: '/tasa-paralela',
    path: '/tasa-paralela',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTasaRoute = AuthenticatedTasaRouteImport.update({
  id: '/tasa',
  path: '/tasa',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRegistrarRoute = AuthenticatedRegistrarRouteImport.update({
  id: '/registrar',
  path: '/registrar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProveedoresRoute =
  AuthenticatedProveedoresRouteImport.update({
    id: '/proveedores',
    path: '/proveedores',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlanCuentasRoute =
  AuthenticatedPlanCuentasRouteImport.update({
    id: '/plan-cuentas',
    path: '/plan-cuentas',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPagarCxpRoute = AuthenticatedPagarCxpRouteImport.update({
  id: '/pagar-cxp',
  path: '/pagar-cxp',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOffBalanceRoute = AuthenticatedOffBalanceRouteImport.update({
  id: '/off-balance',
  path: '/off-balance',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInicioRoute = AuthenticatedInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGypRoute = AuthenticatedGypRouteImport.update({
  id: '/gyp',
  path: '/gyp',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFcRoute = AuthenticatedFcRouteImport.update({
  id: '/fc',
  path: '/fc',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDiferencialCambiarioRoute =
  AuthenticatedDiferencialCambiarioRouteImport.update({
    id: '/diferencial-cambiario',
    path: '/diferencial-cambiario',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCxpRoute = AuthenticatedCxpRouteImport.update({
  id: '/cxp',
  path: '/cxp',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCxcRoute = AuthenticatedCxcRouteImport.update({
  id: '/cxc',
  path: '/cxc',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCuentasBancariasRoute =
  AuthenticatedCuentasBancariasRouteImport.update({
    id: '/cuentas-bancarias',
    path: '/cuentas-bancarias',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicHooksSyncParalelaRoute =
  ApiPublicHooksSyncParalelaRouteImport.update({
    id: '/api/public/hooks/sync-paralela',
    path: '/api/public/hooks/sync-paralela',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSyncBcvRoute = ApiPublicHooksSyncBcvRouteImport.update({
  id: '/api/public/hooks/sync-bcv',
  path: '/api/public/hooks/sync-bcv',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/cuentas-bancarias': typeof AuthenticatedCuentasBancariasRoute
  '/cxc': typeof AuthenticatedCxcRoute
  '/cxp': typeof AuthenticatedCxpRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diferencial-cambiario': typeof AuthenticatedDiferencialCambiarioRoute
  '/fc': typeof AuthenticatedFcRoute
  '/gyp': typeof AuthenticatedGypRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/off-balance': typeof AuthenticatedOffBalanceRoute
  '/pagar-cxp': typeof AuthenticatedPagarCxpRoute
  '/plan-cuentas': typeof AuthenticatedPlanCuentasRoute
  '/proveedores': typeof AuthenticatedProveedoresRoute
  '/registrar': typeof AuthenticatedRegistrarRoute
  '/tasa': typeof AuthenticatedTasaRoute
  '/tasa-paralela': typeof AuthenticatedTasaParalelaRoute
  '/terceros': typeof AuthenticatedTercerosRoute
  '/transacciones': typeof AuthenticatedTransaccionesRoute
  '/api/public/hooks/sync-bcv': typeof ApiPublicHooksSyncBcvRoute
  '/api/public/hooks/sync-paralela': typeof ApiPublicHooksSyncParalelaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/cuentas-bancarias': typeof AuthenticatedCuentasBancariasRoute
  '/cxc': typeof AuthenticatedCxcRoute
  '/cxp': typeof AuthenticatedCxpRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diferencial-cambiario': typeof AuthenticatedDiferencialCambiarioRoute
  '/fc': typeof AuthenticatedFcRoute
  '/gyp': typeof AuthenticatedGypRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/off-balance': typeof AuthenticatedOffBalanceRoute
  '/pagar-cxp': typeof AuthenticatedPagarCxpRoute
  '/plan-cuentas': typeof AuthenticatedPlanCuentasRoute
  '/proveedores': typeof AuthenticatedProveedoresRoute
  '/registrar': typeof AuthenticatedRegistrarRoute
  '/tasa': typeof AuthenticatedTasaRoute
  '/tasa-paralela': typeof AuthenticatedTasaParalelaRoute
  '/terceros': typeof AuthenticatedTercerosRoute
  '/transacciones': typeof AuthenticatedTransaccionesRoute
  '/api/public/hooks/sync-bcv': typeof ApiPublicHooksSyncBcvRoute
  '/api/public/hooks/sync-paralela': typeof ApiPublicHooksSyncParalelaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/cuentas-bancarias': typeof AuthenticatedCuentasBancariasRoute
  '/_authenticated/cxc': typeof AuthenticatedCxcRoute
  '/_authenticated/cxp': typeof AuthenticatedCxpRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/diferencial-cambiario': typeof AuthenticatedDiferencialCambiarioRoute
  '/_authenticated/fc': typeof AuthenticatedFcRoute
  '/_authenticated/gyp': typeof AuthenticatedGypRoute
  '/_authenticated/inicio': typeof AuthenticatedInicioRoute
  '/_authenticated/off-balance': typeof AuthenticatedOffBalanceRoute
  '/_authenticated/pagar-cxp': typeof AuthenticatedPagarCxpRoute
  '/_authenticated/plan-cuentas': typeof AuthenticatedPlanCuentasRoute
  '/_authenticated/proveedores': typeof AuthenticatedProveedoresRoute
  '/_authenticated/registrar': typeof AuthenticatedRegistrarRoute
  '/_authenticated/tasa': typeof AuthenticatedTasaRoute
  '/_authenticated/tasa-paralela': typeof AuthenticatedTasaParalelaRoute
  '/_authenticated/terceros': typeof AuthenticatedTercerosRoute
  '/_authenticated/transacciones': typeof AuthenticatedTransaccionesRoute
  '/api/public/hooks/sync-bcv': typeof ApiPublicHooksSyncBcvRoute
  '/api/public/hooks/sync-paralela': typeof ApiPublicHooksSyncParalelaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/cuentas-bancarias'
    | '/cxc'
    | '/cxp'
    | '/dashboard'
    | '/diferencial-cambiario'
    | '/fc'
    | '/gyp'
    | '/inicio'
    | '/off-balance'
    | '/pagar-cxp'
    | '/plan-cuentas'
    | '/proveedores'
    | '/registrar'
    | '/tasa'
    | '/tasa-paralela'
    | '/terceros'
    | '/transacciones'
    | '/api/public/hooks/sync-bcv'
    | '/api/public/hooks/sync-paralela'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/cuentas-bancarias'
    | '/cxc'
    | '/cxp'
    | '/dashboard'
    | '/diferencial-cambiario'
    | '/fc'
    | '/gyp'
    | '/inicio'
    | '/off-balance'
    | '/pagar-cxp'
    | '/plan-cuentas'
    | '/proveedores'
    | '/registrar'
    | '/tasa'
    | '/tasa-paralela'
    | '/terceros'
    | '/transacciones'
    | '/api/public/hooks/sync-bcv'
    | '/api/public/hooks/sync-paralela'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/cuentas-bancarias'
    | '/_authenticated/cxc'
    | '/_authenticated/cxp'
    | '/_authenticated/dashboard'
    | '/_authenticated/diferencial-cambiario'
    | '/_authenticated/fc'
    | '/_authenticated/gyp'
    | '/_authenticated/inicio'
    | '/_authenticated/off-balance'
    | '/_authenticated/pagar-cxp'
    | '/_authenticated/plan-cuentas'
    | '/_authenticated/proveedores'
    | '/_authenticated/registrar'
    | '/_authenticated/tasa'
    | '/_authenticated/tasa-paralela'
    | '/_authenticated/terceros'
    | '/_authenticated/transacciones'
    | '/api/public/hooks/sync-bcv'
    | '/api/public/hooks/sync-paralela'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiPublicHooksSyncBcvRoute: typeof ApiPublicHooksSyncBcvRoute
  ApiPublicHooksSyncParalelaRoute: typeof ApiPublicHooksSyncParalelaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/transacciones': {
      id: '/_authenticated/transacciones'
      path: '/transacciones'
      fullPath: '/transacciones'
      preLoaderRoute: typeof AuthenticatedTransaccionesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/terceros': {
      id: '/_authenticated/terceros'
      path: '/terceros'
      fullPath: '/terceros'
      preLoaderRoute: typeof AuthenticatedTercerosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tasa-paralela': {
      id: '/_authenticated/tasa-paralela'
      path: '/tasa-paralela'
      fullPath: '/tasa-paralela'
      preLoaderRoute: typeof AuthenticatedTasaParalelaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tasa': {
      id: '/_authenticated/tasa'
      path: '/tasa'
      fullPath: '/tasa'
      preLoaderRoute: typeof AuthenticatedTasaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/registrar': {
      id: '/_authenticated/registrar'
      path: '/registrar'
      fullPath: '/registrar'
      preLoaderRoute: typeof AuthenticatedRegistrarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/proveedores': {
      id: '/_authenticated/proveedores'
      path: '/proveedores'
      fullPath: '/proveedores'
      preLoaderRoute: typeof AuthenticatedProveedoresRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/plan-cuentas': {
      id: '/_authenticated/plan-cuentas'
      path: '/plan-cuentas'
      fullPath: '/plan-cuentas'
      preLoaderRoute: typeof AuthenticatedPlanCuentasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pagar-cxp': {
      id: '/_authenticated/pagar-cxp'
      path: '/pagar-cxp'
      fullPath: '/pagar-cxp'
      preLoaderRoute: typeof AuthenticatedPagarCxpRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/off-balance': {
      id: '/_authenticated/off-balance'
      path: '/off-balance'
      fullPath: '/off-balance'
      preLoaderRoute: typeof AuthenticatedOffBalanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inicio': {
      id: '/_authenticated/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof AuthenticatedInicioRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gyp': {
      id: '/_authenticated/gyp'
      path: '/gyp'
      fullPath: '/gyp'
      preLoaderRoute: typeof AuthenticatedGypRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fc': {
      id: '/_authenticated/fc'
      path: '/fc'
      fullPath: '/fc'
      preLoaderRoute: typeof AuthenticatedFcRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/diferencial-cambiario': {
      id: '/_authenticated/diferencial-cambiario'
      path: '/diferencial-cambiario'
      fullPath: '/diferencial-cambiario'
      preLoaderRoute: typeof AuthenticatedDiferencialCambiarioRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cxp': {
      id: '/_authenticated/cxp'
      path: '/cxp'
      fullPath: '/cxp'
      preLoaderRoute: typeof AuthenticatedCxpRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cxc': {
      id: '/_authenticated/cxc'
      path: '/cxc'
      fullPath: '/cxc'
      preLoaderRoute: typeof AuthenticatedCxcRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cuentas-bancarias': {
      id: '/_authenticated/cuentas-bancarias'
      path: '/cuentas-bancarias'
      fullPath: '/cuentas-bancarias'
      preLoaderRoute: typeof AuthenticatedCuentasBancariasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/hooks/sync-paralela': {
      id: '/api/public/hooks/sync-paralela'
      path: '/api/public/hooks/sync-paralela'
      fullPath: '/api/public/hooks/sync-paralela'
      preLoaderRoute: typeof ApiPublicHooksSyncParalelaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-bcv': {
      id: '/api/public/hooks/sync-bcv'
      path: '/api/public/hooks/sync-bcv'
      fullPath: '/api/public/hooks/sync-bcv'
      preLoaderRoute: typeof ApiPublicHooksSyncBcvRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCuentasBancariasRoute: typeof AuthenticatedCuentasBancariasRoute
  AuthenticatedCxcRoute: typeof AuthenticatedCxcRoute
  AuthenticatedCxpRoute: typeof AuthenticatedCxpRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDiferencialCambiarioRoute: typeof AuthenticatedDiferencialCambiarioRoute
  AuthenticatedFcRoute: typeof AuthenticatedFcRoute
  AuthenticatedGypRoute: typeof AuthenticatedGypRoute
  AuthenticatedInicioRoute: typeof AuthenticatedInicioRoute
  AuthenticatedOffBalanceRoute: typeof AuthenticatedOffBalanceRoute
  AuthenticatedPagarCxpRoute: typeof AuthenticatedPagarCxpRoute
  AuthenticatedPlanCuentasRoute: typeof AuthenticatedPlanCuentasRoute
  AuthenticatedProveedoresRoute: typeof AuthenticatedProveedoresRoute
  AuthenticatedRegistrarRoute: typeof AuthenticatedRegistrarRoute
  AuthenticatedTasaRoute: typeof AuthenticatedTasaRoute
  AuthenticatedTasaParalelaRoute: typeof AuthenticatedTasaParalelaRoute
  AuthenticatedTercerosRoute: typeof AuthenticatedTercerosRoute
  AuthenticatedTransaccionesRoute: typeof AuthenticatedTransaccionesRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCuentasBancariasRoute: AuthenticatedCuentasBancariasRoute,
  AuthenticatedCxcRoute: AuthenticatedCxcRoute,
  AuthenticatedCxpRoute: AuthenticatedCxpRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDiferencialCambiarioRoute:
    AuthenticatedDiferencialCambiarioRoute,
  AuthenticatedFcRoute: AuthenticatedFcRoute,
  AuthenticatedGypRoute: AuthenticatedGypRoute,
  AuthenticatedInicioRoute: AuthenticatedInicioRoute,
  AuthenticatedOffBalanceRoute: AuthenticatedOffBalanceRoute,
  AuthenticatedPagarCxpRoute: AuthenticatedPagarCxpRoute,
  AuthenticatedPlanCuentasRoute: AuthenticatedPlanCuentasRoute,
  AuthenticatedProveedoresRoute: AuthenticatedProveedoresRoute,
  AuthenticatedRegistrarRoute: AuthenticatedRegistrarRoute,
  AuthenticatedTasaRoute: AuthenticatedTasaRoute,
  AuthenticatedTasaParalelaRoute: AuthenticatedTasaParalelaRoute,
  AuthenticatedTercerosRoute: AuthenticatedTercerosRoute,
  AuthenticatedTransaccionesRoute: AuthenticatedTransaccionesRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiPublicHooksSyncBcvRoute: ApiPublicHooksSyncBcvRoute,
  ApiPublicHooksSyncParalelaRoute: ApiPublicHooksSyncParalelaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
